// generated from ../src/rcm_rfc3339.h with `rcmdoc`

[[rcm_rfc3339.h]]
=== `rcm_rfc3339.h` -- RFC3339 time

Module to deal with time strings in RFC3339 format.

==== Defines

[source,c]
----
#define RCM_RFC3339_BUFSIZE 21
----

The default RFC3339 string buffer size.

==== Typedefs

[source,c]
----
typedef enum {
  RCM_RFC3339_OK = 0,
  RCM_RFC3339_ERR_FAILED_ASSERT = -4,
  RCM_RFC3339_ERR_PARSE = -10,
  RCM_RFC3339_ERR_TIME = -11
} rcm_rfc3339_err_t;
----

The RFC3339 error type.

[source,c]
----
typedef struct rcm_rfc3339_t rcm_rfc3339_t;
----

The RCF3339 time type.

==== Functions

[source,c]
----
rcm_rfc3339_err_t rcm_rfc3339_parse(rcm_rfc3339_t *time,
                                    const char *value, char *err);
----

Parse time `value` in RFC3339 format and store the result in `time`
   (if not `NULL`).
   Returns `RCM_RFC3339_ERR_PARSE`, if the parsing failed. 0, otherwise.
   In case of error, the error message is written to `err`.

[source,c]
----
rcm_rfc3339_err_t rcm_rfc3339_now(rcm_rfc3339_t *t, char *err);
----

Return the current time (now) in UTC and store it in `t`.
   Returns `RCM_RFC3339_ERR_TIME`, if the time could not be determined.
   0, otherwise. In case of error, the error message is written to `err`.

[source,c]
----
rcm_rfc3339_err_t rcm_rfc3339_format(char *out, rcm_rfc3339_t time,
                                     char *err);
----

Format time as RFC3339 in UTC to `out` buffer (`\0`-terminated).
   The `out` buffer must have at least size `RCM_RFC3339_BUFSIZE`!

[source,c]
----
bool rcm_rfc3339_after(rcm_rfc3339_t ltime, rcm_rfc3339_t rtime);
----

Return true if `ltime` is after `rtime`, false otherwise.

[source,c]
----
bool rcm_rfc3339_before(rcm_rfc3339_t ltime, rcm_rfc3339_t rtime);
----

Return true if `ltime` is before `rtime`, false otherwise.

[source,c]
----
rcm_rfc3339_t rcm_rfc3339_from_time_t(time_t time);
----

Convert from `time_t` to `rfc3339_t`.

[source,c]
----
const char *rcm_rfc3339_errstr(rcm_rfc3339_err_t errnum);
----

Return an error string describing the given error number errnum.
   For `RCM_RFC3339_OK` an empty string is returned ("", not NULL).

