// generated from ../src/rcm_base64.h with `rcmdoc`

[[rcm_base64.h]]
=== `rcm_base64.h` -- Base64 encoding

This module implements low-level funtions for the base64 standard encoding
with padding as described in RFC 4648. Use the rcm_base64_buf module for
higher-level functions (with memory allocation and error buffers).

==== Typedefs

[source,c]
----
typedef enum {
  RCM_BASE64_OK = 0,
  RCM_BASE64_ERR_FAILED_ASSERT = -4,
  RCM_BASE64_ERR_ILLEGAL_CHAR = -10
} rcm_base64_err_t;
----

The base64 error type.

==== Functions

[source,c]
----
size_t rcm_base64_encode_len(size_t len);
----

Returns the base64 encoded length of a binary input buffer of size len.

[source,c]
----
rcm_base64_err_t rcm_base64_encode(char *out, const unsigned char *in,
                                   size_t len);
----

Writes the base64 encoding of the input buffer in of lenght len to out and
   appends a `\0` character. The output buffer out has to be at least the size
   `rcm_base64_encode_len(len)+1`!

[source,c]
----
size_t rcm_base64_decode_len(size_t len);
----

Returns the decoded length of an base64 encoded input buffer of size len.

[source,c]
----
rcm_base64_err_t rcm_base64_decode(unsigned char *out, const char *in,
                                   size_t len);
----

Decodes the base64 encoded input in of length len and writes it to out (if
   not NULL). If the the output buffer out is not NULL it has to be at least of
   the size `rcm_base64_decode_len(len)`!

[source,c]
----
const char *rcm_base64_errstr(rcm_base64_err_t errnum);
----

Return an error string describing the given error number errnum.
   For `RCM_BASE64_OK` an empty string is returned ("", not NULL).

