// generated from ../src/rcm_mem.h with `rcmdoc`

[[rcm_mem.h]]
=== `rcm_mem.h` -- Memory allocator

This modules defines the memory allocator for _reusable C modules_.

==== Typedefs

[source,c]
----
typedef enum { RCM_MEM_OK = 0, RCM_MEM_ERR_NOMEM = -2 } rcm_mem_err_t;
----

The memory error type.

[source,c]
----
typedef void *rcm_mem_malloc_func(size_t size);
----

Memory allocator (malloc(3)-like).

[source,c]
----
typedef void *rcm_mem_calloc_func(size_t nmemb, size_t size);
----

Memory allocator (calloc(3)-like).

==== Functions

[source,c]
----
void *rcm_mem_malloc(size_t size);
----

Allocates size bytes and returns a pointer to the allocated memory.
   The memory is not initialized.

[source,c]
----
void *rcm_mem_calloc(size_t nmemb, size_t size);
----

Allocates memory for an array of nmemb elements of size bytes and returns a
   pointer to the allocated memory. The memory is set to zero.

[source,c]
----
void rcm_mem_free(void *ptr);
----

Frees the memory space pointed to by ptr.

[source,c]
----
void rcm_mem_freecharptr(char **ptr);
----

Free the memory space pointed to by ptr and set ptr to `NULL`.

[source,c]
----
void rcm_mem_freeucharptr(unsigned char **ptr);
----

Free the memory space pointed to by ptr and set ptr to `NULL`.

[source,c]
----
void rcm_mem_set_malloc(rcm_mem_malloc_func *func);
----

Set malloc function used by this module.
   If func is `NULL` the default allocator is set.

[source,c]
----
void rcm_mem_set_calloc(rcm_mem_calloc_func *func);
----

Set calloc function used by this module.
   If func is `NULL` the default allocator is set.

[source,c]
----
int rcm_mem_num_of_allocs(void);
----

Reset number of allocations. Debug only.
   Returns the total number of allocations so far.

[source,c]
----
void rcm_mem_abort(int n);
----

Abort memory allocation. Debug only.
   Parameter n is the memory allocation to abort.

[source,c]
----
void rcm_mem_reset_abort(void);
----

Reset memory allocation abortion. Debug only.

