// generated from ../src/rcm_assert.h with `rcmdoc`

[[rcm_assert.h]]
=== `rcm_assert.h` -- Robust assertions

The robust assertion macro is inspired by the "JPL Institutional Coding
Standard for the C Programming Language", Rule 16,
(see https://librcm.org/mirrors/JPL_Coding_Standard_C.pdf).

Recommended use:

[source,c]
----
if (!rcm_assert(p >= 0)) {
  return RCM_ASSERT_ERR_FAILED;
}
----

Compile with -DNDEBUG for production and without for development and
testing.

==== Defines

[source,c]
----
#define rcm_assert(e) rcm_assert_handle((e), __FILE__, __LINE__, #e)
----

Robust assertion macro.

==== Typedefs

[source,c]
----
typedef enum {
  RCM_ASSERT_OK = 0,
  RCM_ASSERT_ERR_FAILED_ASSERT = -4
} rcm_assert_err_t;
----

The assert error type.

[source,c]
----
typedef bool rcm_assert_handler_func(const char *file, int line,
                                     const char *expr, void *data);
----

An assertion handler. Should return false to mark the assertion as failed.
   Should return true to ignore failed assertions completely.

==== Functions

[source,c]
----
void rcm_assert_set_handler(rcm_assert_handler_func *handler);
----

Set the assertion handler. The default is rcm_assert_default_handler. Set to
   NULL to disable logging of assertions.

[source,c]
----
void rcm_assert_set_handler_data(void *data);
----

Set data pointer passed to the assertion handler.

[source,c]
----
bool rcm_assert_default_handler(const char *file, int line,
                                const char *expr, void *data);
----

The default assert handler. Prints the failed assertion to stderr and then
   calls abort(3) if not compiled with NDEBUG.

[source,c]
----
bool rcm_assert_handle(bool assert_result, const char *file, int line,
                       const char *expr);
----

Internal function. It calls the rcm_assert_handler, if not NULL and
   assert_result is false.

[source,c]
----
int rcm_assert_num_of_asserts(void);
----

Reset number of assertions. Debug only.

[source,c]
----
void rcm_assert_abort(int n);
----

Abort assertion n. Debug only.

[source,c]
----
void rcm_assert_reset_abort(void);
----

Reset assertion abortion. Debug only.

